model:
    arch: fcn8s
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /content/cityscaped5000_dataset_2
training:
    n_workers: 64
    train_iters: 35000
    batch_size: 16
    val_interval: 500
    print_interval: 25
    loss:
        name: cross_entropy
    optimizer:
        name: adam
        lr: 1.0e-3
        <optimizer_keyarg1>:<value>
    lr_schedule:
        name: constant_lr